### ISSUE TITLE
the input size must be 227*227?

### ISSUE THREAD

**Issue by wang7393** [kratzert/finetune_alexnet_with_tensorflow#10]
if i want use my own dataset and its size is large than 227*227?
how can i do ?

**Comment by kratzert** [comment]
images gets automatically resized to 227x227 in the datagenerator.py.

Note: This repository is about finetuning AlexNet. AlexNet expects input images of size 227x227. If you want to use other input image sizes you cant use AlexNet (at least not the dense layers).
