### ISSUE TITLE
Codes for generating .txt files?

### ISSUE THREAD

**Issue by micklexqg** [kratzert/finetune_alexnet_with_tensorflow#16]
Dear kratzert,
Thanks for the excellent work. And I am trying to fine tune with tensorflow with my own dataset. I have only  images  and no generated .txt files for now. 
Aren't there any codes in the downloaded .zip files for  generating .txt files?

**Comment by kratzert** [comment]
No there is no code provided at the moment for generating the text files, since this should be fairly easy to implement. Maybe I'll at a script but I think you should try it out first on your own.

**Comment by micklexqg** [comment]
yes, I have made it. thanks again!

**Comment by kratzert** [comment]
Okay happy to hear you found your own solution!
