### ISSUE TITLE
alexnet architecture matches?

### ISSUE THREAD

**Issue by jeannotes** [kratzert/finetune_alexnet_with_tensorflow#24]
hi, I did some math computation and check the original paper:
the first convolution filter is [11,11,3,96], there is no maxpool,
second convolution filter is [5,5,96,256], and then we get maxpool
but in your code
```
        conv1 = conv(self.X, 11, 11, 96, 4, 4, padding='VALID', name='conv1')
        norm1 = lrn(conv1, 2, 2e-05, 0.75, name='norm1')
        pool1 = max_pool(norm1, 3, 3, 2, 2, padding='VALID', name='pool1')
        
        # 2nd Layer: Conv (w ReLu)  -> Lrn -> Pool with 2 groups
        conv2 = conv(pool1, 5, 5, 256, 1, 1, groups=2, name='conv2')
        norm2 = lrn(conv2, 2, 2e-05, 0.75, name='norm2')
        pool2 = max_pool(norm2, 3, 3, 2, 2, padding='VALID', name='pool2')
```
, I didn't get it,  which is not the same as the picture, can you explain?

**Comment by kratzert** [comment]
Read the paper again. Page 4 right below Figure 2. Here is the interesting sentence:

> The first convolutional layer filters the 224×224×3 input image with 96 kernels of size 11×11×3 with a stride of 4 pixels [...] The second convolutional layer takes as input the (response-normalized
and pooled) output of the first convolutional layer and filters it with 256 kernels of size 5×5×48

This is exactly what happens in the code.
