### ISSUE TITLE
How can i extract features from full connected layer fc7.

### ISSUE THREAD

**Issue by aminullah6264** [kratzert/finetune_alexnet_with_tensorflow#25]
Hi
I have fine tune my model using this code, now i can predeict new data through trained model.
but i need to extract features of full connected layer fc7.
how it can be possible

**Comment by kratzert** [comment]
Use google search to solve this problem. The topic of this issue + "tensorflow" will give you hundreds of stackoverflow questions regarding the same problem. Issue should be used for bug reports or problems with the code.
