### ISSUE TITLE
I get the bvlc_alexnet.npy and have a question?

### ISSUE THREAD

**Issue by qiu931110** [kratzert/finetune_alexnet_with_tensorflow#27]
I  get  the shape like  this:
conv1
 0 conv1 (11, 11, 3, 96)
 0 conv1 (96,)
conv2
 1 conv2 (5, 5, 48, 256)
 1 conv2 (256,)
conv3
 2 conv3 (3, 3, 256, 384)
 2 conv3 (384,)
conv4
 3 conv4 (3, 3, 192, 384)
 3 conv4 (384,)
conv5
 4 conv5 (3, 3, 192, 256)
 4 conv5 (256,)

how to convert shape   conv2(5,5,48,256)  to   (5,5,96,256)
                                     conv4 (3,3,192,384)  to  (3,3,384,384)
                                     conv5(3,3,192,256)   to  (3,3,384,256)

**Comment by kratzert** [comment]
Convert? You mean split? Just have a look at the implementation of the convolutional layer in the alexnet file. There is an optional keyword "groups" that splits the weights into to evenly large arrays to simulate the split we can see in the original AlexNet paper.

**Comment by kratzert** [comment]
closed due to inactivity. You can reopen this issue, when you provide further information.
