### ISSUE TITLE
TypeError: split() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by Patrifa** [kratzert/finetune_alexnet_with_tensorflow#29]
I'm getting this error. I already researched and can not find a solution. I'm running on Windows and have already changed the position of the parameters and even then it did not work. Would you help me?

**Comment by kratzert** [comment]
Which version of Python and Tensorflow are you using?

**Comment by Patrifa** [comment]
I'm using Python 3.5 and Tensorflow 1.4.

Thank you!

2017-11-13 6:21 GMT-02:00 Frederik Kratzert <notifications@github.com>:

**Comment by kratzert** [comment]
Just tried to reproduce your error with a fresh installation of TensorFlow 1.4 in a clean environment and didn't run into this error. Also from the docs, I see no changes and don't know why this error occurs to you. Maybe try to replace the two lines using tf.split() in the alexnet.py with the following code and try if the error still occurs.

OLD:
        input_groups = tf.split(axis=3, num_or_size_splits=groups, value=x)
        weight_groups = tf.split(axis=3, num_or_size_splits=groups,
                                 value=weights)

NEW:
        input_groups = tf.split(x, groups, axis=3)
        weight_groups = tf.split(weights, groups, axis=3)

And tell me if this changes anything

**Comment by Patrifa** [comment]
Good Morning, Frederik!
I installed everything again and it worked! I think he was giving some
conflict and so it was wrong.
Thank you so much for returning!
Hugs!


2017-11-17 7:28 GMT-02:00 Frederik Kratzert <notifications@github.com>:
