### ISSUE TITLE
Dataaugmentation promble

### ISSUE THREAD

**Issue by xiexie123** [kratzert/finetune_alexnet_with_tensorflow#31]
hi,
   I want to add dataaugmentation in datagenerator.py. According to your comments in def _parse_function_train(self, filename, label):

            """
        Dataaugmentation comes here.
        """
  say I want to flip_up_and down and flip_left_right, in this way, and corp from 4 corner, one input image could have 6 output images.

so my question is: does the _parse_function_train() function still work for data.map(self._parse_function_train,....). if not, how I add my dataaugmentation in the code?

thanks!

-------------------------------------------
My point is in _parse_function_train() function, one input image could have 6 output images. Is that ok?

**Comment by kratzert** [comment]
I guess I don't understand your question very well. You can do what ever you want in the _parse_function_train, e.g. adding dataaugmentation, and the _parse_function_inference won't be affected by this. This is exactly the reason, why there are two different functions.

**Comment by kratzert** [comment]
closed due to inactivity
