### ISSUE TITLE
InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got empty file？

### ISSUE THREAD

**Issue by pastaxingxin** [kratzert/finetune_alexnet_with_tensorflow#33]
Hello，recently I used your code to test image classifying.
Now,there are some stand errors.You can see below:

![image](https://user-images.githubusercontent.com/17949301/33232336-76d6040e-d23f-11e7-96f3-85df627b2a5e.png)

As for my train file, it is like this:
![image](https://user-images.githubusercontent.com/17949301/33232318-0c04c17e-d23f-11e7-8dad-860f9a65cac2.png)
This task is important for me, but I am still puzzled in it.
Could you help solve this problem? Thanks to you in advance.

**Comment by kratzert** [comment]
Are the paths correct? Like all of them? You could iterate over your file and test every path with the `os` library if it exist. If only one file does not exist or is a damaged image, you will get this error.

**Comment by pastaxingxin** [comment]
I have 92004 images and 23316 images in all for train and validation respectively.when I run the code, it results in above errors.
After that,I have 2000 images and 200 images from my all images for train and validation respectively, it can run sucessfully.
Could you please explain this outcome?
there are not path problems or missing image.

**Comment by pastaxingxin** [comment]
I have 3000 images and 300 images from my all images for train and validation respectively, it can run sucessfully,too.
when I have 4000 images and 400 images from my all images for train and validation respectively, above bugs  start to appear.

**Comment by pastaxingxin** [comment]
it has been solved.
some images are broken.
