### ISSUE TITLE
Can I see the fc7 output?

### ISSUE THREAD

**Issue by Rockefella091** [kratzert/finetune_alexnet_with_tensorflow#36]
Hello, I've never worked with tensorflow before and I cannot really understand how to see some of the output. I am trying to print the the values that fc7 outputs for every image in the testing set. Is there any way I can do this?

**Comment by kratzert** [comment]
Closed, because it's not related to any problem with the code. Please use Stackoverflow for this kind of questions or just search with e.g. google since this is answered 100s of times.

Hint: value = sess.run(variable_name, feed_dict={your_dict_values})
