### ISSUE TITLE
Principal Component Analysis

### ISSUE THREAD

**Issue by Vincentcent1** [kratzert/finetune_alexnet_with_tensorflow#40]
Hi, the Alexnet paper listed PCA as a data augmentation method, I'm wondering whether this is implemented in your model as I can't seem to find it.

**Comment by kratzert** [comment]
No it isn't. And just to be clear, this repository is not about reproducing the AlexNet paper. It is about finetuning the pretrained AlexNet model.

What ever data augmentation you need for your own data set has to be added by you to the `_parse_function_train` to the appropriate line.
