### ISSUE TITLE
Where is the bvlc_alexnet.npy ?

### ISSUE THREAD

**Issue by Ostnie** [kratzert/finetune_alexnet_with_tensorflow#41]
Hello , I try to use your code in my data ,and I create the txt file, by the way , I want to know the format of the txt ,in my txt file , the first column is the photo directory ，and the second is the label . Does this correct? Besides this ,I run the program and it told me that :No such file or directory: 'bvlc_alexnet.npy'
I guess it was a weight file which has been trained before ,but I don't find it ,how should I do ?
Many thanks!

**Comment by kratzert** [comment]
Sometimes I really don't understand the people writing here. Like do you even bother to read the description in the README.md? You will a) find instructions about the weight file (little hint: you have to download them separately) and b) find an example how the txt file should look.
So please, just spend a few minutes reading this, as I spend a lot of time to provide all this code and the blog article

**Comment by Ostnie** [comment]
I am really sorry, I sincerely apologize, I used to ReadMe.md documentation, this time I missed, brought you upset I am really sad, I hope this will not affect your mood,
