### ISSUE TITLE
Test the output model

### ISSUE THREAD

**Issue by HanYuanyuaner** [kratzert/finetune_alexnet_with_tensorflow#44]
Hi, 
I finished training Alexnet and output some .meta files in checkpoints folder. Then I want to predicted a picture with the new model parameters. I followed the validate_alexnet_on_imagenet.ipynb file step by step and changed  "model = AlexNet(x, keep_prob, 1000, [])" to "model = AlexNet(x, keep_prob, 2, [])", as in my processes the num_classes are 2. The error message is as follows:

Dimension 1 in both shapes must be equal, but are 2 and 1000. Shapes are [4096,2] and [4096,1000]. for 'fc8_1/Assign' (op: 'Assign') with input shapes: [4096,2], [4096,1000].

I am not sure whether I need to change any other codes in validate_alexnet_on_imagenet.ipynb

Thank you

**Comment by kratzert** [comment]
Actually you should use another approach for using the trained network. This has been already discussed several times in the blog and also here in the issue section.

See e.g. [Link](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/38#issuecomment-365066342) for a code example.
