### ISSUE TITLE
Is this suitable for large scale dataset?

### ISSUE THREAD

**Issue by feynman233** [kratzert/finetune_alexnet_with_tensorflow#48]
Hi! Thanks for your wonderful program!
In the "self._parse_function_train" function ,do you load all of your training dataset ? 
I want to apply your code to video dataset，and should I load all of the training dataset in this function?
thanks!

**Comment by kratzert** [comment]
Hi @feynman233,
please remember that the issue section should be used for bug reports on the dataset not for arbitrary QA. Please do have a look how tensorflows dataset api works (no it doesn't load the entire dataset at once in memory, instead it's queuing a specific amount of samples in RAM that can be defined by the user). And I have never worked with video data, so this is something you need to ask somewhere else.
