### ISSUE TITLE
Checkpoint and Test_set

### ISSUE THREAD

**Issue by Auth0rM0rgan** [kratzert/finetune_alexnet_with_tensorflow#51]
Hey @kratzert,

As I understand from your code, you are using train_set and val_set in your network. Also, save the last 5 checkpoints of your model. I want to know How can I use these checkpoints and evaluate my test_data based on saved checkpoints? Can you help me?

Thanks in advance.

**Comment by kratzert** [comment]
Just do a little search on your own. This has been discussed here many times. See e.g. [link](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/38#issuecomment-365066342)
