### ISSUE TITLE
How to test on an image?

### ISSUE THREAD

**Issue by engrchrishenry** [kratzert/finetune_alexnet_with_tensorflow#52]
Hello!

I fine-tuned AlexNet using finetune.py for a binary classification problem. Now using the checkpoints file,  how can I test this network on a random image?

**Comment by kratzert** [comment]
this has been asked and answered several times. please use the search next time before you open an issue

See e.g. [this thread](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/38#issuecomment-365066342)
