### ISSUE TITLE
Trainable==False in get_variable

### ISSUE THREAD

**Issue by cbhanu** [kratzert/finetune_alexnet_with_tensorflow#55]
In the alexnet.py code : 
for the load_initial_weights function : 
        var = tf.get_variable('biases', trainable=False)

Is the trainable here set to false, since the actual variable was already added to the tf.GraphKeys.TRAINABLE_VARIABLES when setting up the layers in conv or fc functions when doing get_variable there ? 

What difference does it make if we anyways keep it trainable=True here ? 

Acc to my understanding , the code does finetuning over all layers, but trains last layer from scratch. 
Is that correct ?

**Comment by kratzert** [comment]
Yes that is correct, therefore all layers that are loaded from the pre-trained weights are set with "trainable=False"
