### ISSUE TITLE
Nan in summary histogram for: fc8/weights_0

### ISSUE THREAD

**Issue by ChengYeung1222** [kratzert/finetune_alexnet_with_tensorflow#58]
hi!It's very kind of you for sharing  the repository.I used it to train the Dogs vs.Cats datasets and it worked.But when I used the ILSVRC2012 dataset to fine-tune the structure, I found some errors:

`Traceback (most recent call last):
  File "/home/chengy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/chengy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/chengy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fc8/weights_0
	 [[Node: fc8/weights_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fc8/weights_0/tag, fc8/weights/read/_41)]]`

I've tried to replace the loss function to the following:
`    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=score,
                                                                  labels=tf.clip_by_value(y,1e-10,1.0)))`
and changed the learning rate to a very low number as 1e-4.But these operations did not make it better.
I just use 20 categories of the whole 1 000 categories of Imagenet to fine-tune the model.Does anyone have met the same problem or have solutions to fix it?Thanks in advance.

**Comment by Prem95** [comment]
I had this problem when I used AdamOptimizer() instead of GradientDescent(). For the loss function, I used ```tf.nn.softmax_cross_entropy_with_logits_v2()``` as per the warning in my TF. Learningg rate was 1e-3. NaN in histogram could mean that the gradient is always 0 or always vanishes. ```fc8``` is giving weight/0 as NaN which means the weights are not there. Try checking the path for the pre-trained weights and also the training images.

**Comment by ChengYeung1222** [comment]
> I had this problem when I used AdamOptimizer() instead of GradientDescent(). For the loss function, I used `tf.nn.softmax_cross_entropy_with_logits_v2()` as per the warning in my TF. Learningg rate was 1e-3. NaN in histogram could mean that the gradient is always 0 or always vanishes. `fc8` is giving weight/0 as NaN which means the weights are not there. Try checking the path for the pre-trained weights and also the training images.

Thank you for your tips.And I changed the learning rate into a lower one.There's no error occurs but it's just random guesses.The accuracy was always around 0.5(20 classes).The path for the weights and input images path .txt are both in a correct way.These can be normally loaded. I don't understand why the model does not work well on these classes from Imagenet.

**Comment by kratzert** [comment]
accuracy of 50% on 20 classes isn't random guessing. Or do you mean 2 instead of 20? 
to which value did you change the learning rate. You have any screenshot of the train loss over time? Is there something happening at all? You could try to overfit first meaning you use maybe only 1-2 images per class and see if you achieve a training loss of 0. Like this you can make sure your network is able to learn at all.

**Comment by ChengYeung1222** [comment]
> accuracy of 50% on 20 classes isn't random guessing. Or do you mean 2 instead of 20?
> to which value did you change the learning rate. You have any screenshot of the train loss over time? Is there something happening at all? You could try to overfit first meaning you use maybe only 1-2 images per class and see if you achieve a training loss of 0. Like this you can make sure your network is able to learn at all.

Sorry for typing incorrectly..The accuracy is about 5% for 20 classes.

**Comment by ChengYeung1222** [comment]
The loss with 'fc8' being trained was about 2.99.And I just tried to calculate the images losses without fine tuning and they're in the range from 10 to 30.Is that normal?

**Comment by kratzert** [comment]
Are you sure you load the trained model when you do inference? If your loss without fine tuning is 10 to 30 and after fine tuning you have a loss of ~3 this means your model has learned something and your accuracy should be above random guessing.

**Comment by ChengYeung1222** [comment]
I changed the optimizer back to Gradient descent and it converged.The accuracy was about 83% about the 20 classes.I used adam before.It's weird but finally it finally get correct output.
