### ISSUE TITLE
typo in the description 

### ISSUE THREAD

**Issue by wogong** [kratzert/finetune_alexnet_with_tensorflow#60]
A typo in the repository's description is misleading.

> Code for finetuning AlexNet in TensorFlow >= 1.12 ...

from the code I found this should be

> Code for finetuning AlexNet in TensorFlow >= 1.2rc0 ...

PS: Due to the API changes of TensorFlow, would you mind if I create a PR to get this repo compatible with 1.10?

**Comment by kratzert** [comment]
Hey, you are right it was 1.2rc0 for which I change the code (if 1.2rc0 was the first with dataset api). 

Does changing the repo to work with 1.10 requires many changes? The point is I then have to update the blog post accordingly. Or are there only changes in keywords? I switched to PyTorch and am not up to date about TensorFlow version stuff. 

But in general I would be very grateful for a PR to adapt for the changes

**Comment by wogong** [comment]
minor changes, I think :)
