### ISSUE TITLE
about pretrained weights

### ISSUE THREAD

**Issue by DoubleYing** [kratzert/finetune_alexnet_with_tensorflow#62]
I‘ve download your pretrained weights, and I want to directly use it to predict the pictures in imageNet, but I find its' results are really terrible.  So I want to know which dataset did you use to generate the pretrained weights ? Or need I to pretrain the network by myself, and transfer it to other image dataset?

**Comment by Prem95** [comment]
Pre-trained weights are the weights that are trained over the 1000 classes in ImageNet. So, I'm not really sure why it would not work

**Comment by Prem95** [comment]
Is your problem solved? If yes, @kratzert please close this. Thanks.
