### ISSUE TITLE
How to restore fine tuned checkpoints of custom dataset.   

### ISSUE THREAD

**Issue by nasir3843** [kratzert/finetune_alexnet_with_tensorflow#64]
Hello,
I have successfully fine tuned Alexnet using custom dataset. Now I am not sure how can I use this code to get prediction using the fine tuned checkpoints. Any help would be appreciated. Thank You

**Comment by kratzert** [comment]
This has been asked several times already and I'm not sure why people don't search in the Issues before opening the same question over and over again.

[Solution](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/38#issuecomment-365066342l)
