### ISSUE TITLE
Initializing problem

### ISSUE THREAD

**Issue by ChengYeung1222** [kratzert/finetune_alexnet_with_tensorflow#67]
The layers not in the skip_layer list are loaded from the .npy pretrained weight file. And other layers are trained from scratch. I'm searching for a long time where are the initializers for the train_layers.The variable scope was create as following:
`    with tf.variable_scope(name) as scope:  
        # Create tf variables for the weights and biases of the conv layer  
        weights = tf.get_variable('weights', shape=[filter_height,  
                                                    filter_width,  
                                                    input_channels/groups,  
                                                    num_filters])  
        biases = tf.get_variable('biases', shape=[num_filters])`
and the tf.get_variable() ops were created without set the initializer args. Does anyone know where the initializers set in the code and how to change them?

**Comment by francescomilano172** [comment]
The answer might be at https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/ops/variable_scope.py#L289
