### ISSUE TITLE
A question about the train_layers

### ISSUE THREAD

**Issue by LemonLov** [kratzert/finetune_alexnet_with_tensorflow#77]
Hello, my problem is that you load pre-trained parameters from bvlc_alexnet.npy for the layers that don't require training, but there seem to be no initialization parameters for the layers that need to be trained. Is it the program will automatically initialize those parameters? (To be zero or what?)
I just don't understand this part a bit, I hope that if you have time you can answer for me. Thanks.

**Comment by kratzert** [comment]
if nothing is passed explicitly, new layers are initialized to their default initialization. You can find this in the tensorflow documentation. Not sure which one is currently used since I'm not working with Tensorflow at the moment

**Comment by LemonLov** [comment]
Thank you for spending your time to answer me, I will go deeper to this problem later.
