### ISSUE TITLE
Error in notebook: "ValueError: Variable conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope"

### ISSUE THREAD

**Issue by txizzle** [kratzert/finetune_alexnet_with_tensorflow#8]
Hi, I am having some trouble running the third cell of the notebook. Error is:

```
ValueErrorTraceback (most recent call last)
<ipython-input-7-f7a1b7dd0c14> in <module>()
      7 
      8 #create model with default config ( == no skip_layer and 1000 units in the last layer)
----> 9 model = AlexNet(x, keep_prob, 1000, [])
     10 
     11 #define activation of last layer as score

/mnt/ilcompf6d0/user/txiao/DockerFiles/finetune_alexnet_with_tensorflow/alexnet.py in __init__(self, x, keep_prob, num_classes, skip_layer, weights_path)
     39 
     40     # Call the create function to build the computational graph of AlexNet
---> 41     self.create()
     42 
     43   def create(self):

/mnt/ilcompf6d0/user/txiao/DockerFiles/finetune_alexnet_with_tensorflow/alexnet.py in create(self)
     44 
     45     # 1st Layer: Conv (w ReLu) -> Pool -> Lrn
---> 46     conv1 = conv(self.X, 11, 11, 96, 4, 4, padding = 'VALID', name = 'conv1')
     47     pool1 = max_pool(conv1, 3, 3, 2, 2, padding = 'VALID', name = 'pool1')
     48     norm1 = lrn(pool1, 2, 2e-05, 0.75, name = 'norm1')

/mnt/ilcompf6d0/user/txiao/DockerFiles/finetune_alexnet_with_tensorflow/alexnet.py in conv(x, filter_height, filter_width, num_filters, stride_y, stride_x, name, padding, groups)
    131   with tf.variable_scope(name) as scope:
    132     # Create tf variables for the weights and biases of the conv layer
--> 133     weights = tf.get_variable('weights', shape = [filter_height, filter_width, input_channels/groups, num_filters])
    134     biases = tf.get_variable('biases', shape = [num_filters])
    135 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
   1047       collections=collections, caching_device=caching_device,
   1048       partitioner=partitioner, validate_shape=validate_shape,
-> 1049       use_resource=use_resource, custom_getter=custom_getter)
   1050 get_variable_or_local_docstring = (
   1051     """%s

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
    946           collections=collections, caching_device=caching_device,
    947           partitioner=partitioner, validate_shape=validate_shape,
--> 948           use_resource=use_resource, custom_getter=custom_getter)
    949 
    950   def _get_partitioned_variable(self,

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
    354           reuse=reuse, trainable=trainable, collections=collections,
    355           caching_device=caching_device, partitioner=partitioner,
--> 356           validate_shape=validate_shape, use_resource=use_resource)
    357 
    358   def _get_partitioned_variable(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource)
    339           trainable=trainable, collections=collections,
    340           caching_device=caching_device, validate_shape=validate_shape,
--> 341           use_resource=use_resource)
    342 
    343     if custom_getter is not None:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource)
    651                          " Did you mean to set reuse=True in VarScope? "
    652                          "Originally defined at:\n\n%s" % (
--> 653                              name, "".join(traceback.format_list(tb))))
    654       found_var = self._vars[name]
    655       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "alexnet.py", line 133, in conv
    weights = tf.get_variable('weights', shape = [filter_height, filter_width, input_channels/groups, num_filters])
  File "alexnet.py", line 46, in create
    conv1 = conv(self.X, 11, 11, 96, 4, 4, padding = 'VALID', name = 'conv1')
  File "alexnet.py", line 41, in __init__
    self.create()

```

This error was in both the May 22 commit (TF 1.0) and the latest commit, TF 1.12rc0. I am on TF 1.1.0.

Cheers!

**Comment by kratzert** [comment]
I don't get this error with neither of the two TensorFlow versions. Note that code block 3 should only be executed once! If you want to execute the block of the graph creation again, TensorFlow will raise this error, because the graph (with it's layer names) already exists. If you run this notebook block after block there should be absolutely no problem.
In the case you want to re-run codeblock 3 (for what ever reason) just insert a simple tf.reset_default_graph() at the beginning of the block. This will reset the graph you have already create and though you can create it again.

**Comment by lhfly5201314** [comment]
*@kratzert* This guy's anwser is great!!!

**Comment by OValery16** [comment]
Thanks kratzert

**Comment by evgnikonorov** [comment]
Thanks!

**Comment by peytonhong** [comment]
@kratzert You saved me, thanks!

**Comment by luisghdzrojas** [comment]
@kratzert Thanks !!!

**Comment by ghost** [comment]
@kratzert

**Comment by ghost** [comment]
I think your advice is pretty reasonable and useful

**Comment by HassankSalim** [comment]
Thanks @kratzert

**Comment by arsalan993** [comment]
Thanks @kratzert

**Comment by qweszxc7410** [comment]
Thanks @kratzert 
Use  tf.reset_default_graph()

**Comment by ramzis** [comment]
Thank-you @kratzert !

**Comment by azitagh** [comment]
hi, everybody. I have the same problem with my code. I'm a beginner in python is there anybody can help me? what is mean:( If you run this notebook block after block there should be absolutely no problem.) can u exactly explain to me what I should do?
I run the code for the first time and get this error: AssertionError: File not found.
so I run it again and get the value error.

**Comment by kratzert** [comment]
Hi @azitagh 
maybe you should learn some Python basics first. Seems like you are missing a lot of fundamentals and this code repository and the notebook are not meant to be a introduction to Python.

**Comment by azitagh** [comment]
thank u so much Kratzert. I have a question if you can help me. how can I understand that one python code is for Linux or windows? and how can I exchange a Linux code to windows? do u know any good book(simple) or a good site that can help me in this case(or even anybody)?

**Comment by VaibhavKhamgaonkar** [comment]
Hi,

I am getting the similar error but i dont know how to solve it. I tried the mentioned solution but seems that its not working for me. I am using transfer learning techique

import tensorflow as tf
#tf.reset_default_graph()
from keras.preprocessing.image import ImageDataGenerator

from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import Dense, Flatten ,GlobalAveragePooling2D

from keras.models import Sequential
from keras.applications import ResNet50, MobileNet,InceptionV3

modelPath = 'resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'

numClasses = 39

def getModel():
    
    resnetModel = Sequential()
    resnetModel.add(ResNet50(include_top=False, weights=modelPath, pooling='avg'))
    resnetModel.add(Dense(numClasses, activation='softmax'))
    
    resnetModel.layers[0].trainable = False
    
    resnetModel.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    
    print(resnetModel.summary())

    return resnetModel


model = getModel()


# Getting below error:

ValueError: Variable bn_conv1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/Users/vk250027/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1004, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/Users/vk250027/anaconda3/lib/python3.6/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/Users/vk250027/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)

**Comment by kratzert** [comment]
@VaibhavKhamgaonkar This has nothing to do with the code presented in this code base. Please ask at a appropriate place, e.g. StackOverflow

**Comment by CoderXWChu** [comment]
Thanks @kratzert

**Comment by sbharadwajj** [comment]
Thank you @kratzert

**Comment by hacker-wei** [comment]
have you ever solve this problem??? @VaibhavKhamgaonkar ,I have meet same problem,thanks

**Comment by hacker-wei** [comment]
Traceback (most recent call last):
  File "/home/lvv/code/TFusion/rank-reid/pretrain/pair_train.py", line 251, in <module>
    dataset_parent='/home/lvv/code/TFusion/rank-reid/dataset')
  File "/home/lvv/code/TFusion/rank-reid/pretrain/pair_train.py", line 238, in pair_pretrain_on_dataset
    batch_size=batch_size, num_classes=class_count
  File "/home/lvv/code/TFusion/rank-reid/pretrain/pair_train.py", line 165, in pair_tune
    model = pair_model(source_model_path, num_classes)
  File "/home/lvv/code/TFusion/rank-reid/pretrain/pair_train.py", line 135, in pair_model
    feature1 = Flatten()(base_model(img1))
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2236, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1004, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 180, in _zero_debias
    "biased", initializer=biased_initializer, trainable=False)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/lvv/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable bn_conv1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1004, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs) @kratzert  .I don't know how to solve it?

**Comment by dscha09** [comment]
> I don't get this error with neither of the two TensorFlow versions. Note that code block 3 should only be executed once! If you want to execute the block of the graph creation again, TensorFlow will raise this error, because the graph (with it's layer names) already exists. If you run this notebook block after block there should be absolutely no problem.
> In the case you want to re-run codeblock 3 (for what ever reason) just insert a simple tf.reset_default_graph() at the beginning of the block. This will reset the graph you have already create and though you can create it again.

@kratzert What do you mean by "block 3?"

**Comment by dscha09** [comment]
@kratzert I inserted `tf.reset_default_graph()` but I get this error:

> ValueError: Tensor("lanenet_loss/inference/encode/conv1_1/conv/W:0", shape=(3, 3, 3, 64), dtype=float32_ref) must be from the same graph as Tensor("input_tensor_1:0", shape=(4, 256, 512, 3), dtype=float32).

**Comment by aiden213** [comment]
The problem looks like you are using the Spyder. And just a reminder, you can restart kernel every time when you got an error report. Because I got the same error report: "Variable conv1/weights already exists, disallowed." and it has gone after I restart kernel.

**Comment by dodojiaojiao** [comment]
Hi,I met the same problem when I call the resnet_v2_50() many times in my code,I put the function in a loop because I want to compute an image many times and compute the mean values.Did I need to reset some variables before I call resnet_v2_50 again?

**Comment by dennishnf** [comment]
> I don't get this error with neither of the two TensorFlow versions. Note that code block 3 should only be executed once! If you want to execute the block of the graph creation again, TensorFlow will raise this error, because the graph (with it's layer names) already exists. If you run this notebook block after block there should be absolutely no problem.
> In the case you want to re-run codeblock 3 (for what ever reason) just insert a simple tf.reset_default_graph() at the beginning of the block. This will reset the graph you have already create and though you can create it again.

In a nutshell, restart you kernel :D

**Comment by dodojiaojiao** [comment]
thank you very much, this method I have tried before and it can solve this problem,but it is time consuming.The best way may be define the session and runmode outside the loop which will save much time.发自我的华为手机-------- 原始邮件 --------主题：Re: [kratzert/finetune_alexnet_with_tensorflow] Error in notebook: "ValueError: Variable conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope" (#8)发件人：Dennis Núñez Fernández 收件人：kratzert/finetune_alexnet_with_tensorflow 抄送：dodojiaojiao ,Comment 
I don't get this error with neither of the two TensorFlow versions. Note that code block 3 should only be executed once! If you want to execute the block of the graph creation again, TensorFlow will raise this error, because the graph (with it's layer names) already exists. If you run this notebook block after block there should be absolutely no problem.
In the case you want to re-run codeblock 3 (for what ever reason) just insert a simple tf.reset_default_graph() at the beginning of the block. This will reset the graph you have already create and though you can create it again.

In a nutshell, restart you kernel :D

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/8?email_source=notifications\u0026email_token=AJCVVOEZADTTHV6HIVIDASLPZA4YPA5CNFSM4DRIBV2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXBGLRA#issuecomment-499279300",
"url": "https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/8?email_source=notifications\u0026email_token=AJCVVOEZADTTHV6HIVIDASLPZA4YPA5CNFSM4DRIBV2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXBGLRA#issuecomment-499279300",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by prativadas** [comment]
where exactly we have to insert the 1 line tf.reset_default_graph() in our code? can anyone be specific

**Comment by pradhannihar** [comment]
@kratzert, thank you. tf.reset_default_graph() solve the issue. But always remember to put it outside of tf.Session().
