### ISSUE TITLE
While running finetune.py I am getting following errors.Can anyone help me in correcting them

### ISSUE THREAD

**Issue by superk007** [kratzert/finetune_alexnet_with_tensorflow#82]
Traceback (most recent call last):
  File "C:/Users/admin/video_querying/finetune.py", line 55, in <module>
    shuffle=True)
  File "C:\Users\admin\video_querying\datagenerator.py", line 53, in __init__
    self._read_txt_file()
  File "C:\Users\admin\video_querying\datagenerator.py", line 94, in _read_txt_file
    with open(self.txt_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/train.txt'

**Comment by fengyuICT** [comment]
It seems python can't find train.txt correctly, All you need is to read README that explain "If you do not want to touch the code any further than necessary you have to provide two .txt files to the script (train.txt and val.txt)".

**Comment by kratzert** [comment]
Thanks @fengyuICT 

I sometimes don't understand the people who try to use this code..This is a) pretty obvious from the error message and b) is explained in the repo as stated by @fengyuICT
